"""Wire constants for the Chainway UR4 protocol."""

from __future__ import annotations

from enum import IntEnum

FRAME_HEADER = b"\xa5\x5a"
ALT_FRAME_HEADER = b"\xc8\x8c"
FRAME_HEADERS = (FRAME_HEADER, ALT_FRAME_HEADER)
FRAME_TAIL = b"\r\n"
MIN_FRAME_LENGTH = 8
MAX_FRAME_LENGTH = 2048
FRAME_OVERHEAD = 8
FRAME_PREFIX_SIZE = 4

DEFAULT_BAUDRATE = 115200
DEFAULT_RESPONSE_TIMEOUT = 2.0
DEFAULT_KEEPALIVE_INTERVAL = 5.0
DEFAULT_DEAD_LINK_TIMEOUT = 20.0
MAINTENANCE_TICK = 0.5
INVENTORY_START_DELAY = 0.5
CONFIG_COMMIT_DELAY = 0.7
RESTORE_COMMIT_DELAY = 1.5

SINGLE_INVENTORY_PAYLOAD = b"\x00\x64"
START_INVENTORY_PAYLOAD = b"\x00\x00"
START_INVENTORY_PHASE_PAYLOAD = b"\xff\xff"
START_INVENTORY_FREQUENCY_PAYLOAD = b"\xff\xfe"
START_INVENTORY_PHASE_AND_FREQUENCY_PAYLOAD = b"\xff\xfd"
PHASE_SIZE = 2
INVENTORY_KEEPALIVE_BYTE = b"\x00"
VERIFY_VOLTAGE_PAYLOAD = b"\x01"
COLLECTED_TAGS_FULL_PAYLOAD = b"\x01"
UPDATE_BLOCK_SIZE = 64

UDP_DISCOVERY_PORT = 1111
DISCOVERY_PACKET_SIZE = 12

BYTE_MAX = 0xFF
WORD_MAX = 0xFFFF
DWORD_MAX = 0xFFFFFFFF
STATUS_OK = 0x01
TAG_SUCCESS = b"\x01\x00"
UNSUPPORTED_REPLY = b"\x00"
TAG_ERROR_MEANINGS = {
    0x01: "the tag rejected the operation, the memory is locked, the password is wrong,"
    " or the chip does not support the command",
    0x22: "no tag answered, or the word window runs past the end of the bank",
}
WORD_SIGN_BIT = 0x8000
WORD_MODULUS = 0x10000
IPV4_OCTETS = 4
MAX_FIXED_FREQUENCY_KHZ = 0xFFFFFF
POWER_RECORD_SIZE = 5
MIN_TAG_RECORD_SIZE = 3
USER_BLOCK_MARGIN = 3
BATCH_MIN_PAYLOAD = 5
READER_ADDRESS_LONG_SIZE = 15
READER_ADDRESS_SIZE = 7
DEVICE_ID_SIZE = 4
FREQUENCY_BYTES = 3
RETURN_LOSS_RECORD_SIZE = 2
ANTENNA_COUNT = 16
AUTH_CHALLENGE_SIZE = 10
AUTH_KEY_AND_DATA_SIZE = 11
MODULE_PARAM_ID_SIZE = 4
MODULE_PARAM_DATA_SIZE = 4
MODULE_WORK_TIME_BYTES = 5
MODULE_WORK_TIME_MAX = 0xFFFFFFFFFF
DEACTIVATE_COMMAND_SIZE = 2
SENSOR_EPC_SIZE = 16
SENSOR_CALIBRATION_DATA_SIZE = 8
TAG_TEMP_RECORD_SIZE = 4
TEMP_CODE_MAX = 0x3FF
TEMP_CODE_SIGN_BIT = 0x200
TEMP_CODE_SPAN = 0x400
TEMP_CODE_RESOLUTION = 0.25
TAG_SENSOR_VOLTAGE_FACTOR = 2.5 / 8192

MIN_POWER_DBM = 1.0
MAX_POWER_DBM = 30.0
BARCODE_NO_READ_PAYLOAD = b"\x02\x02\x00"
MIN_ANTENNA = 1
MAX_ANTENNA = 16
MIN_WORD_ADDRESS = 0
MAX_WORD_ADDRESS = 0xFFFF
MAX_WORD_COUNT = 0xFFFF
ACCESS_PASSWORD_SIZE = 4
TID_SIZE = 12
INVALID_RSSI_SPAN = 2000.0


class Command(IntEnum):
    """Request command bytes, responses carry the request command plus one."""

    HARDWARE_VERSION = 0x00
    GET_VERSION = 0x02
    GET_DEVICE_ID = 0x04
    SET_PROTOCOL_TYPE = 0x06
    VERIFY_VOLTAGE = 0x08
    SET_POWER = 0x10
    GET_POWER = 0x12
    SET_FIXED_FREQUENCY = 0x14
    GET_FIXED_FREQUENCY = 0x16
    SET_PARAM = 0x18
    GET_PARAM = 0x1A
    SET_UART_BAUDRATE = 0x1C
    GET_UART_BAUDRATE = 0x1E
    SET_GEN2_PARAMETERS = 0x20
    GET_GEN2_PARAMETERS = 0x22
    SET_CARRIER_WAVE = 0x24
    GET_RETURN_LOSS = 0x26
    SET_ANTENNA_MASK = 0x28
    GET_ANTENNA_MASK = 0x2A
    SET_REGION = 0x2C
    GET_REGION = 0x2E
    GET_TEMPERATURE = 0x34
    SET_TEMPERATURE_PROTECT = 0x38
    GET_TEMPERATURE_PROTECT = 0x3A
    SET_MODULE_WORK_TIME = 0x3C
    GET_MODULE_WORK_TIME = 0x3E
    SET_ANTENNA_WORK_TIME = 0x4A
    GET_ANTENNA_WORK_TIME = 0x4C
    ANTENNA_CONNECTION_STATE = 0x4E
    SET_RF_LINK = 0x52
    GET_RF_LINK = 0x54
    SET_FAST_ID = 0x5C
    GET_FAST_ID = 0x5E
    SET_TAG_FOCUS = 0x60
    GET_TAG_FOCUS = 0x62
    SET_FAST_INVENTORY_MODE = 0x64
    GET_FAST_INVENTORY_MODE = 0x66
    SOFTWARE_RESET = 0x68
    SET_DUAL_SINGLE_MODE = 0x6A
    GET_DUAL_SINGLE_MODE = 0x6C
    SET_INVENTORY_FILTER = 0x6E
    SET_INVENTORY_MODE = 0x70
    GET_INVENTORY_MODE = 0x72
    RESTORE_FACTORY_SETTINGS = 0x74
    SENSOR_CALIBRATION = 0x7C
    SINGLE_INVENTORY = 0x80
    START_INVENTORY = 0x82
    TAG_STREAM = 0x83
    STOP_INVENTORY = 0x8C
    AUTHENTICATE_TAG = 0x8E
    SET_PROTECTED_MODE = 0x90
    READ_TAG = 0x84
    WRITE_TAG = 0x86
    LOCK_TAG = 0x88
    KILL_TAG = 0x8A
    BLOCK_WRITE_TAG = 0x93
    BLOCK_ERASE_TAG = 0x95
    SET_QT = 0x97
    GET_QT = 0x99
    READ_QT = 0x9B
    WRITE_QT = 0x9D
    BLOCK_PERMALOCK_TAG = 0x9F
    TAG_SENSOR = 0xA3
    DEACTIVATE_TAG = 0xB0
    SET_DWELL_TIME = 0xB2
    CONFIG = 0xA1
    JUMP_TO_BOOTLOADER = 0xC0
    START_UPDATE = 0xC2
    UPDATE_BLOCK = 0xC4
    STOP_UPDATE = 0xC6
    STM32_VERSION = 0xC8
    READ_COLLECTED_TAGS = 0xE0
    READ_COLLECTED_TAGS_FULL = 0xE2
    PERIPHERAL = 0xE4
    FLASH_STORAGE = 0xE9
    READ_FLASH_TAGS = 0xEB


class ConfigSubcommand(IntEnum):
    """Payload byte 0 of the 0xA1 configuration family."""

    SET_READER_ADDRESS = 0x01
    GET_READER_ADDRESS = 0x02
    SET_DESTINATION_ADDRESS = 0x03
    GET_DESTINATION_ADDRESS = 0x04
    SET_WORK_MODE = 0x05
    GET_WORK_MODE = 0x06
    SET_BUZZER = 0x07
    GET_BUZZER = 0x08
    SET_GPO = 0x09
    GET_GPI = 0x0A
    SET_TRIGGER_CONFIG = 0x0B
    GET_TRIGGER_CONFIG = 0x0C
    SET_VOLUME = 0x11
    GET_VOLUME = 0x12


CONFIG_COMMITTING_SUBCOMMANDS = frozenset(
    {
        ConfigSubcommand.SET_READER_ADDRESS,
        ConfigSubcommand.SET_DESTINATION_ADDRESS,
        ConfigSubcommand.SET_WORK_MODE,
        ConfigSubcommand.SET_BUZZER,
        ConfigSubcommand.SET_TRIGGER_CONFIG,
    }
)


class PeripheralSubcommand(IntEnum):
    """Payload byte 0 of the 0xE4 peripheral family."""

    BATTERY = 0x01
    BARCODE = 0x02
    BUZZER_DURATION = 0x03
    IDLE_SLEEP_SET = 0x05
    IDLE_SLEEP_GET = 0x06
    LED = 0x07


class SensorSubcommand(IntEnum):
    """Payload byte 0 of the 0x7C sensor and calibration family."""

    SENSOR_CODE = 0x01
    GET_CALIBRATION = 0x02
    ON_CHIP_RSSI = 0x03
    TEMPERATURE_CODE = 0x04
    RSSI_AND_TEMPERATURE = 0x05
    WRITE_CALIBRATION = 0x06


class TagSensorSubcommand(IntEnum):
    """Payload byte 0 of the 0xA3 tag sensor family."""

    START_LOGGING = 0x03
    STOP_LOGGING = 0x04
    CHECK_OP_MODE = 0x05
    READ_VOLTAGE = 0x06
    READ_MULTI_TEMP = 0x07


class FlashSubcommand(IntEnum):
    """Payload byte 0 of the 0xE9 collected tag storage family."""

    ALL_COUNT = 0x00
    NEW_COUNT = 0x01
    DELETE_ALL = 0xFF


class FlashDataSubcommand(IntEnum):
    """Payload byte 0 of the 0xEB collected tag storage pull."""

    READ_ALL = 0xFF


class ProtocolTypeSelector(IntEnum):
    """Payload byte 0 of the 0x06 protocol type command."""

    SET = 0x00
    GET = 0x01
